export const paths = {
  home: "/",
  login: "/login",
  register: "/register",
  forgotPassword: "/forgot-password",
  registerCompany: "/register-company",
  dashboard: "/dashboard",
  adminRoot: "/admin",
  adminDashboard: "/admin/dashboard",
  adminRegisterUser: "/admin/register-user",
  adminContracts: "/admin/contracts",
  adminPrices: "/admin/prices",
  adminAdditiveRequests: "/admin/additive-requests",
  adminAdditiveRequestDetail: "/admin/additive-requests/:id",
  adminAdditiveRequestNew: "/admin/additive-requests/new",
  adminApprovals: "/admin/approvals",
  adminItems: "/admin/items",
  adminFormalization: "/admin/formalization",
  adminSignatures: "/admin/signatures",
  adminProfile: "/admin/profile",
} as const;
